name: "Review app creator"
on:
  workflow_dispatch:
    inputs:
      decidimBranch:
        description: 'Decidim branch name'
        required: true
        default: ''
      decidimIssue:
        description: 'Decidim issue/PR number'
        required: false
        default: ''
      repository:
        description: 'The repository where the branch is (default is decidim/decidim)'
        required: false
        default: 'decidim/decidim'

env:
  DEFAULT_BRANCH: develop
  DEFAULT_REPO: decidim/decidim
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_HOST: localhost
  PR_BODY: ""

jobs:
  main:
    name: Update decidim and create PR
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - name: Add branch link to PR body
        run: echo "PR_BODY=Review app used to test Decidim branch [${{ github.event.inputs.decidimBranch }}](/${{ github.event.inputs.repository }}/tree/${{ github.event.inputs.decidimBranch }})" >> $GITHUB_ENV

      - name: Add issue number to PR body
        if: ${{ github.event.inputs.decidimIssue != '' }}
        run: echo "PR_BODY=${{ env.PR_BODY }} for decidim/decidim#${{ github.event.inputs.decidimIssue }}" >> $GITHUB_ENV

      - name: "Check if user has write access"
        uses: "lannonbr/repo-permission-check-action@2.0.0"
        with:
          permission: "write"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Check if decidim branch exists"
        run: "git ls-remote --exit-code --heads https://github.com/${{ github.event.inputs.repository }}.git ${{ github.event.inputs.decidimBranch }}"

      - uses: actions/checkout@v2.0.0

      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ steps.versions.outputs.ruby }}
          bundler-cache: true

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.versions.outputs.nodejs }}

      - name: Change Decidim branch in Gemfile
        run: "sed -i -r 's|(DECIDIM_VERSION.*=.*\\bbranch:.*)${{ env.DEFAULT_BRANCH }}(.*)|\\1${{ github.event.inputs.decidimBranch }}\\2|' Gemfile"

      - name: Change Decidim repository in Gemfile
        run: "sed -i -r 's|(DECIDIM_VERSION.*=.*\\bgithub.com/)${{ env.DEFAULT_REPO }}(.*)|\\1${{ github.event.inputs.repository }}\\2|' Gemfile"

      - name: Unset deployment for bundler
        run: bundle config unset deployment

      - name: Install Ruby dependencies
        run: bundle install --path vendor/bundle --jobs 4

      - name: Update database schema
        run: bundle exec rake db:create db:schema:load decidim:upgrade db:migrate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          assignees: "${{ github.actor }}"
          body: "${{ env.PR_BODY }}"
          branch: "review_app/${{ github.event.inputs.decidimBranch }}"
          commit-message: "Update decidim to ${{ github.event.inputs.decidimBranch }} branch"
          committer: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          title: "Review app for ${{ github.event.inputs.decidimBranch }} by ${{ github.actor }}"
